remote_theme: pages-themes/midnight@v0.2.0

title: [Hive PBR]
description: [First ever resource pack edit to add support for PBR textures]

show_downloads: [true]
show_tar: [false]
github:
  zip_url: http://playhive.com
